# Generated by Django 3.2 on 2024-11-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
